// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { CreateResponse, CreateBody, FindAllResponse, FindOneResponse, UpdateResponse, UpdateBody, RemoveResponse } from './types';

const tagService = {
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/tags', body);
    return data;
  },

  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/tags');
    return data;
  },

  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/tags/${id}`);
    return data;
  },

  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/tags/${id}`, body);
    return data;
  },

  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/tags/${id}`);
    return data;
  },
};

export default tagService;
