// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateTagDto = Record<string, unknown>;

export type UpdateTagDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /tags — response */
export type CreateResponse = unknown;
/** POST /tags — payload */
export type CreateBody = CreateTagDto;

/** GET /tags — response */
export type FindAllResponse = unknown;

/** GET /tags/{id} — response */
export type FindOneResponse = unknown;

/** PATCH /tags/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /tags/{id} — payload */
export type UpdateBody = UpdateTagDto;

/** DELETE /tags/{id} — response */
export type RemoveResponse = unknown;
