// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { CreateResponse, CreateBody, FindAllResponse, CheckExistsResponse, CheckExistsParams, FindOneResponse, UpdateResponse, UpdateBody, RemoveResponse } from './types';

const categoriesService = {
  /** Criar categoria (admin) */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/categories', body);
    return data;
  },

  /** Listar todas as categorias */
  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/categories');
    return data;
  },

  /** Verificar se categoria existe por nome */
  async checkExists(params: CheckExistsParams = {} as CheckExistsParams): Promise<CheckExistsResponse> {
    const { data } = await apiClient.get('/api/categories/exists', { params });
    return data;
  },

  /** Buscar categoria por ID (admin) */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/categories/${id}`);
    return data;
  },

  /** Atualizar categoria (admin) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/categories/${id}`, body);
    return data;
  },

  /** Remover categoria (admin) */
  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/categories/${id}`);
    return data;
  },
};

export default categoriesService;
