// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateCategoryDto = Record<string, unknown>;

export type UpdateCategoryDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /categories — response */
export type CreateResponse = unknown;
/** POST /categories — payload */
export type CreateBody = CreateCategoryDto;

/** GET /categories — response */
export type FindAllResponse = unknown;

/** GET /categories/exists — response */
export type CheckExistsResponse = unknown;
/** GET /categories/exists — query params */
export interface CheckExistsParams {
  /** Nome da categoria (case-insensitive) */
  name: string;
}

/** GET /categories/{id} — response */
export type FindOneResponse = unknown;

/** PATCH /categories/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /categories/{id} — payload */
export type UpdateBody = UpdateCategoryDto;

/** DELETE /categories/{id} — response */
export type RemoveResponse = unknown;
