// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { GetStatsResponse, GetUserSessionsResponse, RevokeSessionResponse } from './types';

const adminService = {
  /** Obter estatísticas do painel (Apenas Admin) */
  async getStats(): Promise<GetStatsResponse> {
    const { data } = await apiClient.get('/api/admin/stats');
    return data;
  },

  /** Listar sessões de acesso de um usuário (Apenas Admin) */
  async getUserSessions(userId: string): Promise<GetUserSessionsResponse> {
    const { data } = await apiClient.get(`/api/admin/users/${userId}/sessions`);
    return data;
  },

  /** Revogar sessão do usuário instantaneamente (Apenas Admin) */
  async revokeSession(sessionId: string): Promise<RevokeSessionResponse> {
    const { data } = await apiClient.post(`/api/admin/sessions/${sessionId}/revoke`);
    return data;
  },
};

export default adminService;
