// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/stats — response */
export type GetStatsResponse = unknown;

/** GET /admin/users/{userId}/sessions — response */
export type GetUserSessionsResponse = unknown;

/** POST /admin/sessions/{sessionId}/revoke — response */
export type RevokeSessionResponse = unknown;
