// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import axios from 'axios';
import Cookies from 'js-cookie';

const apiClient = axios.create({
  baseURL: '',
});

apiClient.interceptors.request.use(
  (config) => {
  const token = Cookies.get('accessToken');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  if (typeof window !== 'undefined') {
    let deviceId = 'unknown';
    try {
      deviceId = localStorage.getItem('deviceId') ?? '';
      if (!deviceId) {
        deviceId = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem('deviceId', deviceId);
      }
    } catch (_) {}

    const ua = window.navigator.userAgent;
    const isMobile = /iPhone|iPad|iPod|Android/i.test(ua);
    config.headers['x-device-id']         = deviceId;
    config.headers['x-device-user-agent'] = ua;
    config.headers['x-device-browser']    = ua.includes('Chrome') ? 'Chrome' : ua.includes('Safari') ? 'Safari' : 'Other';
    config.headers['x-device-os']         = ua.includes('Windows') ? 'Windows' : ua.includes('Mac') ? 'MacOS' : 'Other';
    config.headers['x-device-type']       = isMobile ? 'mobile' : 'desktop';
  }
    return config;
  },
  (error) => Promise.reject(error),
);

apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      Cookies.remove('accessToken');
      if (typeof window !== 'undefined') {
        window.location.href = '/login';
      }
    }
    return Promise.reject(error);
  },
);

export default apiClient;
