// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import 'server-only';
import axios from 'axios';
import https from 'node:https';

const httpsAgent =
  process.env.BACKEND_IGNORE_SSL === 'true'
    ? new https.Agent({ rejectUnauthorized: false })
    : undefined;

export interface FetchBackendOptions {
  method?: string;
  headers?: Record<string, string>;
  body?: unknown;
}

/**
 * Faz uma chamada HTTP ao backend a partir de um Route Handler do Next.js.
 * Retorna um objeto com interface similar ao fetch() para compatibilidade.
 */
export async function fetchBackend(
  url: string,
  { method = 'GET', headers = {}, body }: FetchBackendOptions = {},
) {
  // Garante que headers seja mutável
  headers = { ...headers };

  // Propaga o JWT do cookie nas chamadas server-side (Route Handlers)
  const { cookies } = await import('next/headers');
  const cookieStore = await cookies();
  const token = cookieStore.get('accessToken')?.value;
  if (token && !headers['Authorization'] && !headers['authorization']) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const response = await axios({
    url,
    method,
    headers,
    data: body,
    httpsAgent,
    timeout: 15000,
    validateStatus: () => true,
  });

  return {
    ok: response.status >= 200 && response.status < 300,
    status: response.status,
    headers: {
      get: (key: string) => (response.headers[key.toLowerCase()] as string) ?? null,
    },
    json: async () => response.data as unknown,
    text: async () =>
      typeof response.data === 'string'
        ? response.data
        : JSON.stringify(response.data),
  };
}
