// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { CreateResponse, CreateBody, FindAllResponse, UpdateResponse, UpdateBody, FindOneResponse, RemoveResponse, ScrapeImageResponse, ScrapeImageBody, CheckExistsResponse, CheckExistsParams } from './types';

const collectionService = {
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/collections', body);
    return data;
  },

  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/collections');
    return data;
  },

  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/collections/${id}`, body);
    return data;
  },

  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/collections/${id}`);
    return data;
  },

  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/collections/${id}`);
    return data;
  },

  async scrapeImage(body: ScrapeImageBody): Promise<ScrapeImageResponse> {
    const { data } = await apiClient.post('/api/collections/scrape-image', body);
    return data;
  },

  async checkExists(params: CheckExistsParams = {} as CheckExistsParams): Promise<CheckExistsResponse> {
    const { data } = await apiClient.get('/api/collections/exists', { params });
    return data;
  },
};

export default collectionService;
