// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateCollectionDto = Record<string, unknown>;

export type UpdateCollectionDto = Record<string, unknown>;

export type ScrapeImageDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /collections — response */
export type CreateResponse = unknown;
/** POST /collections — payload */
export type CreateBody = CreateCollectionDto;

/** GET /collections — response */
export type FindAllResponse = unknown;

/** PATCH /collections/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /collections/{id} — payload */
export type UpdateBody = UpdateCollectionDto;

/** GET /collections/{id} — response */
export type FindOneResponse = unknown;

/** DELETE /collections/{id} — response */
export type RemoveResponse = unknown;

/** POST /collections/scrape-image — response */
export type ScrapeImageResponse = unknown;
/** POST /collections/scrape-image — payload */
export type ScrapeImageBody = ScrapeImageDto;

/** GET /collections/exists — response */
export type CheckExistsResponse = unknown;
/** GET /collections/exists — query params */
export interface CheckExistsParams {
  title: string;
}
