// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { CreateResponse, CreateBody, FindAllResponse, UpdateResponse, UpdateBody, RemoveResponse, FindOneResponse, ProcessBulkResponse, ScrapeImageResponse, ScrapeImageBody, GetCodeResponse } from './types';

const componentsService = {
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/components', body);
    return data;
  },

  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/components');
    return data;
  },

  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/components/${id}`, body);
    return data;
  },

  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/components/${id}`);
    return data;
  },

  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/components/${id}`);
    return data;
  },

  async processBulk(): Promise<ProcessBulkResponse> {
    const { data } = await apiClient.post('/api/components/process-bulk');
    return data;
  },

  async scrapeImage(body: ScrapeImageBody): Promise<ScrapeImageResponse> {
    const { data } = await apiClient.post('/api/components/scrape-image', body);
    return data;
  },

  async getCode(id: string): Promise<GetCodeResponse> {
    const { data } = await apiClient.get(`/api/components/${id}/code`);
    return data;
  },
};

export default componentsService;
