// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateComponentDto = Record<string, unknown>;

export type UpdateComponentDto = Record<string, unknown>;

export type ScrapeImageDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /components — response */
export type CreateResponse = unknown;
/** POST /components — payload */
export type CreateBody = CreateComponentDto;

/** GET /components — response */
export type FindAllResponse = unknown;

/** PATCH /components/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /components/{id} — payload */
export type UpdateBody = UpdateComponentDto;

/** DELETE /components/{id} — response */
export type RemoveResponse = unknown;

/** GET /components/{id} — response */
export type FindOneResponse = unknown;

/** POST /components/process-bulk — response */
export type ProcessBulkResponse = unknown;

/** POST /components/scrape-image — response */
export type ScrapeImageResponse = unknown;
/** POST /components/scrape-image — payload */
export type ScrapeImageBody = ScrapeImageDto;

/** GET /components/{id}/code — response */
export type GetCodeResponse = unknown;
