// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import { NextResponse } from 'next/server';
import { fetchBackend } from '@/lib/fetchBackend';

// POST /categories — Criar categoria (admin)
// GET /categories — Listar todas as categorias

export async function POST(request: Request) {
  try {
    // Criar categoria (admin)
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const url = `${API_URL}/categories`;

    const body = await request.json();
    headers['Content-Type'] = 'application/json';
    const response = await fetchBackend(url, { method: 'POST', headers, body: JSON.stringify(body) });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[POST /categories]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}

export async function GET(request: Request) {
  try {
    // Listar todas as categorias
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const url = `${API_URL}/categories`;

    const response = await fetchBackend(url, { method: 'GET', headers });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[GET /categories]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}
