// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { RegisterResponse, RegisterBody, LoginResponse, LoginBody, GetProfileResponse, LogoutResponse } from './types';

const authService = {
  /** Registrar um novo usuário */
  async register(body: RegisterBody): Promise<RegisterResponse> {
    const { data } = await apiClient.post('/api/auth/register', body);
    return data;
  },

  /** Fazer login na plataforma */
  async login(body: LoginBody): Promise<LoginResponse> {
    const { data } = await apiClient.post('/api/auth/login', body);
    return data;
  },

  /** Obter dados do perfil do usuário logado */
  async getProfile(): Promise<GetProfileResponse> {
    const { data } = await apiClient.get('/api/auth/profile');
    return data;
  },

  /** Fazer logout da plataforma e revogar a sessão atual */
  async logout(): Promise<LogoutResponse> {
    const { data } = await apiClient.post('/api/auth/logout');
    return data;
  },
};

export default authService;
