// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface RegisterDto {
  /** Nome completo do usuário */
  name: string;
  /** Endereço de email */
  email: string;
  /** Senha (mínimo 6 caracteres) */
  password: string;
}

export interface LoginDto {
  /** O email do usuário cadastrado. */
  email: string;
  /** A senha do usuário. */
  password: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /auth/register — response */
export type RegisterResponse = unknown;
/** POST /auth/register — payload */
export type RegisterBody = RegisterDto;

/** POST /auth/login — response */
export type LoginResponse = unknown;
/** POST /auth/login — payload */
export type LoginBody = LoginDto;

/** GET /auth/profile — response */
export type GetProfileResponse = unknown;

/** POST /auth/logout — response */
export type LogoutResponse = unknown;
