// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import { NextResponse } from 'next/server';
import { fetchBackend } from '@/lib/fetchBackend';

// POST /users/me/likes/{componentId}

export async function POST(request: Request, context: any) {
  try {
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const params = await context.params;
    const url = `${API_URL}/users/me/likes/${params.componentId}`;

    const response = await fetchBackend(url, { method: 'POST', headers });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[POST /users/me/likes/{componentId}]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}
