// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import { NextResponse } from 'next/server';
import { fetchBackend } from '@/lib/fetchBackend';

// GET /admin/stats — Obter estatísticas do painel (Apenas Admin)

export async function GET(request: Request) {
  try {
    // Obter estatísticas do painel (Apenas Admin)
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const url = `${API_URL}/admin/stats`;

    const response = await fetchBackend(url, { method: 'GET', headers });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[GET /admin/stats]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}
