// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import { NextResponse } from 'next/server';
import { fetchBackend } from '@/lib/fetchBackend';

// GET /tags/{id}
// PATCH /tags/{id}
// DELETE /tags/{id}

export async function GET(request: Request, context: any) {
  try {
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const params = await context.params;
    const url = `${API_URL}/tags/${params.id}`;

    const response = await fetchBackend(url, { method: 'GET', headers });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[GET /tags/{id}]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}

export async function PATCH(request: Request, context: any) {
  try {
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const params = await context.params;
    const url = `${API_URL}/tags/${params.id}`;

    const body = await request.json();
    headers['Content-Type'] = 'application/json';
    const response = await fetchBackend(url, { method: 'PATCH', headers, body: JSON.stringify(body) });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[PATCH /tags/{id}]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}

export async function DELETE(request: Request, context: any) {
  try {
    const API_URL = process.env.API_URL || 'https://api.fastfigma.com';

    const authHeader = request.headers.get('authorization');
    const headers: Record<string, string> = {};
    if (authHeader) {
      headers['Authorization'] = authHeader;
    }

    const params = await context.params;
    const url = `${API_URL}/tags/${params.id}`;

    const response = await fetchBackend(url, { method: 'DELETE', headers });

    let data;
    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      data = await response.json();
    } else {
      data = await response.text();
    }

    if (!response.ok) {
      return NextResponse.json(
        { success: false, message: data?.message ?? 'Erro na requisição' },
        { status: response.status },
      );
    }

    return NextResponse.json(data, { status: response.status });
  } catch (error) {
    console.error('[DELETE /tags/{id}]', error);
    return NextResponse.json({ success: false, message: 'Erro interno do servidor' }, { status: 500 });
  }
}
