import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

export interface GenerateFetchBackendOptions {
  /** Output path relative to cwd @default 'src/lib/fetchBackend.ts' */
  outputPath?: string;
  /**
   * Name of the cookie containing the JWT.
   * If configured, it propagates the JWT from the cookie into internal Server-Side API calls.
   */
  cookieName?: string;
  /**
   * HTTP request timeout (in ms).
   * @default 15000
   */
  timeout?: number;
}

/**
 * Generates fetchBackend.ts — the server-side HTTP client for Next.js Route Handlers.
 *
 * This client:
 *  - Uses axios to support BACKEND_IGNORE_SSL in development environments.
 *  - Exposes an interface matching the native fetch() to comply with handler signatures.
 *  - Reads via next/headers and propagates the JWT token (if cookieName is set).
 */
export function generateFetchBackend({
  outputPath = 'src/lib/fetchBackend.ts',
  cookieName,
  timeout = 15_000,
}: GenerateFetchBackendOptions, cwd: string): string {
  const hasCookie = !!cookieName;

  const cookieBlock = hasCookie
    ? `
  // Propagate the JWT from Next.js server cookies into backend API calls
  const { cookies } = await import('next/headers');
  const cookieStore = await cookies();
  const token = cookieStore.get('${cookieName}')?.value;
  if (token && !headers['Authorization'] && !headers['authorization']) {
    headers['Authorization'] = \`Bearer \${token}\`;
  }`
    : `
  // cookieName not configured — no JWT is propagated automatically.
  // Supply the Authorization header manually inside the route handler if needed.`;

  const content = `// Auto-generated by nextjs-openapi-codegen — do not edit manually
import 'server-only';
import axios from 'axios';
import https from 'node:https';

const httpsAgent =
  process.env.BACKEND_IGNORE_SSL === 'true'
    ? new https.Agent({ rejectUnauthorized: false })
    : undefined;

export interface FetchBackendOptions {
  method?: string;
  headers?: Record<string, string>;
  body?: unknown;
}

/**
 * Performs an HTTP request to the backend from a Next.js Server Component or Route Handler.
 * Returns an object with a fetch-compatible interface.
 */
export async function fetchBackend(
  url: string,
  { method = 'GET', headers = {}, body }: FetchBackendOptions = {},
) {
  // Ensure headers are mutable
  headers = { ...headers };
${cookieBlock}

  const response = await axios({
    url,
    method,
    headers,
    data: body,
    httpsAgent,
    timeout: ${timeout},
    validateStatus: () => true,
  });

  return {
    ok: response.status >= 200 && response.status < 300,
    status: response.status,
    headers: {
      get: (key: string) => (response.headers[key.toLowerCase()] as string) ?? null,
    },
    json: async () => response.data as unknown,
    text: async () =>
      typeof response.data === 'string'
        ? response.data
        : JSON.stringify(response.data),
  };
}
`;

  const absolutePath = join(cwd, outputPath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content, 'utf-8');
  return outputPath;
}
