import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

export interface GenerateApiClientOptions {
  /** Output path relative to cwd @default 'src/lib/apiClient.ts' */
  outputPath?: string;
  /**
   * Name of the cookie containing the JWT token.
   * If not provided, auth interceptors are generated but no cookie is read automatically.
   */
  cookieName?: string;
  /**
   * Redirect path when receiving a 401 Unauthorized status.
   * @default '/auth'
   */
  unauthorizedRedirect?: string;
  /**
   * Inject device tracking headers (deviceId, userAgent, etc.) automatically.
   */
  deviceTracking?: boolean;
}

/**
 * Generates apiClient.ts — the axios client for the browser.
 *
 * This client:
 *  - Reads the JWT from the `cookieName` (if configured) and sends it as a Bearer token.
 *  - Redirects to `unauthorizedRedirect` on HTTP 401.
 *  - Optionally injects device tracking headers.
 */
export function generateApiClient({
  outputPath = 'src/lib/apiClient.ts',
  cookieName,
  unauthorizedRedirect = '/auth',
  deviceTracking = false,
}: GenerateApiClientOptions, cwd: string): string {
  const hasCookie = !!cookieName;

  const cookieImport = hasCookie ? `import Cookies from 'js-cookie';\n` : '';

  const authBlock = hasCookie
    ? `
    const token = Cookies.get('${cookieName}');
    if (token) {
      config.headers.Authorization = \`Bearer \${token}\`;
    }`
    : `
    // cookieName not configured — no token will be sent automatically.
    // To authenticate manually, call: apiClient.defaults.headers.common['Authorization'] = 'Bearer <token>';`;

  const deviceBlock = deviceTracking
    ? `
    if (typeof window !== 'undefined') {
      let deviceId = 'unknown';
      try {
        deviceId = localStorage.getItem('deviceId') ?? '';
        if (!deviceId) {
          deviceId = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2) + Date.now().toString(36);
          localStorage.setItem('deviceId', deviceId);
        }
      } catch (_) {}

      const ua = window.navigator.userAgent;
      const isMobile = /iPhone|iPad|iPod|Android/i.test(ua);
      config.headers['x-device-id']         = deviceId;
      config.headers['x-device-user-agent'] = ua;
      config.headers['x-device-browser']    = ua.includes('Chrome') ? 'Chrome' : ua.includes('Safari') ? 'Safari' : 'Other';
      config.headers['x-device-os']         = ua.includes('Windows') ? 'Windows' : ua.includes('Mac') ? 'MacOS' : 'Other';
      config.headers['x-device-type']       = isMobile ? 'mobile' : 'desktop';
    }`
    : '';

  const removeCookie = hasCookie
    ? `      Cookies.remove('${cookieName}');`
    : '      // Clear session data manually if needed here.';

  const content = `// Auto-generated by nextjs-openapi-codegen — do not edit manually
import axios from 'axios';
${cookieImport}
const apiClient = axios.create({
  baseURL: '',
});

apiClient.interceptors.request.use(
  (config) => {${authBlock}${deviceBlock}
    return config;
  },
  (error) => Promise.reject(error),
);

apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
${removeCookie}
      if (typeof window !== 'undefined') {
        window.location.href = '${unauthorizedRedirect}';
      }
    }
    return Promise.reject(error);
  },
);

export default apiClient;
`;

  const absolutePath = join(cwd, outputPath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content, 'utf-8');
  return outputPath;
}
