import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { toNextPath, extractOperations, fetchSpec } from './utils.js';

function buildBackendUrl(path: string) {
  const withParams = path.replace(/\{(\w+)\}/g, (_, p) => `\${params.${p}}`);
  return `\`\${API_URL}${withParams}\``;
}

function renderHandler(op: any, { apiEnvVar, apiFallback }: any) {
  const { method, path, pathParams, hasBody, hasQueryParams, bodyContentType, summary } = op;
  const hasPathParams = pathParams.length > 0;
  const isMultipart   = hasBody && bodyContentType === 'multipart/form-data';
  const isJson        = hasBody && !isMultipart; // fallback to JSON

  const fnArgs = hasPathParams ? 'request: Request, context: any' : 'request: Request';

  const lines: string[] = [];
  lines.push(`export async function ${method}(${fnArgs}) {`);
  lines.push(`  try {`);

  if (summary) lines.push(`    // ${summary}`);

  lines.push(`    const API_URL = process.env.${apiEnvVar} || '${apiFallback}';`);
  lines.push('');

  // Auth pass-through
  lines.push(`    const authHeader = request.headers.get('authorization');`);
  lines.push(`    const headers: Record<string, string> = {};`);
  lines.push(`    if (authHeader) {`);
  lines.push(`      headers['Authorization'] = authHeader;`);
  lines.push(`    }`);
  lines.push('');

  // Path params (Next.js 15+: async parameters)
  if (hasPathParams) {
    lines.push(`    const params = await context.params;`);
  }

  // URL compilation
  const backendUrl = buildBackendUrl(path);
  if (hasQueryParams) {
    lines.push(`    const { searchParams } = new URL(request.url);`);
    lines.push(`    const queryString = searchParams.toString();`);
    lines.push(`    const url = queryString ? \`${backendUrl.slice(1, -1)}?\${queryString}\` : ${backendUrl};`);
  } else {
    lines.push(`    const url = ${backendUrl};`);
  }
  lines.push('');

  // Body parsing (distinguishes between JSON and multipart)
  const fetchOpts: string[] = [`method: '${method}'`, 'headers'];
  if (isJson) {
    lines.push(`    const body = await request.json();`);
    lines.push(`    headers['Content-Type'] = 'application/json';`);
    fetchOpts.push('body: JSON.stringify(body)');
  } else if (isMultipart) {
    // For multipart: pass the FormData directly.
    // DO NOT set the Content-Type header — Axios/Fetch handles the boundary.
    lines.push(`    const formData = await request.formData();`);
    fetchOpts.push('body: formData');
    lines.push(`    // multipart/form-data — boundary is autogenerated, do not force Content-Type`);
  }

  lines.push(`    const response = await fetchBackend(url, { ${fetchOpts.join(', ')} });`);
  lines.push('');

  // Agnostic response parsing
  lines.push(`    let data;`);
  lines.push(`    const contentType = response.headers.get('content-type') ?? '';`);
  lines.push(`    if (contentType.includes('application/json')) {`);
  lines.push(`      data = await response.json();`);
  lines.push(`    } else {`);
  lines.push(`      data = await response.text();`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    if (!response.ok) {`);
  lines.push(`      return NextResponse.json(`);
  lines.push(`        { success: false, message: data?.message ?? 'Request encountered an error' },`);
  lines.push(`        { status: response.status },`);
  lines.push(`      );`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    return NextResponse.json(data, { status: response.status });`);
  lines.push(`  } catch (error) {`);
  lines.push(`    console.error('[${method} ${path}]', error);`);
  lines.push(`    return NextResponse.json({ success: false, message: 'Internal Server Error' }, { status: 500 });`);
  lines.push(`  }`);
  lines.push(`}`);

  return lines.join('\n');
}

function renderRoute({ operations, apiEnvVar, apiFallback }: any) {
  const summaries = operations
    .map((op: any) => `// ${op.method} ${op.path}${op.summary ? ` — ${op.summary}` : ''}`)
    .join('\n');

  const handlers = operations
    .map((op: any) => renderHandler(op, { apiEnvVar, apiFallback }))
    .join('\n\n');

  return `// Auto-generated by nextjs-openapi-codegen — do not edit manually
import { NextResponse } from 'next/server';
import { fetchBackend } from '@/lib/fetchBackend';

${summaries}

${handlers}
`;
}

export async function generateRoutes({
  spec,
  stripPathPrefix,
  apiEnvVar,
  apiFallback,
  routesOut,
  cwd,
}: any) {
  const parsed     = typeof spec === 'string' ? await fetchSpec(spec) : spec;
  const operations = extractOperations(parsed, { stripPathPrefix });

  // Group by Next.js path (multiple methods mapping to the same route.ts file)
  const byPath = new Map<string, any[]>();
  for (const op of operations) {
    const nextPath = toNextPath(op.path);
    if (!byPath.has(nextPath)) byPath.set(nextPath, []);
    byPath.get(nextPath)!.push(op);
  }

  const files: string[] = [];

  for (const [nextPath, ops] of byPath) {
    const relativePath = join(routesOut, nextPath, 'route.ts');
    const absolutePath = join(cwd, relativePath);
    const content      = renderRoute({ operations: ops, apiEnvVar, apiFallback });

    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content, 'utf-8');
    files.push(relativePath);
  }

  return files;
}
