// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { HealthResponse } from './types';

const healthService = {
  /** Health check da API */
  async health(): Promise<HealthResponse> {
    const { data } = await apiClient.get('/api/health');
    return data;
  },
};

export default healthService;
