// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /health — response */
export type HealthResponse = unknown;
