// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import apiClient from '@/lib/apiClient';
import type { GetProfileResponse, UpdateProfileResponse, UpdateProfileBody, ChangePasswordResponse, ChangePasswordBody, ForgotPasswordResponse, ForgotPasswordBody, ResetPasswordResponse, ResetPasswordBody, ToggleLikeResponse, GetFavoritesResponse } from './types';

const usersService = {
  async getProfile(): Promise<GetProfileResponse> {
    const { data } = await apiClient.get('/api/users/me');
    return data;
  },

  async updateProfile(body: UpdateProfileBody): Promise<UpdateProfileResponse> {
    const { data } = await apiClient.patch('/api/users/me', body);
    return data;
  },

  async changePassword(body: ChangePasswordBody): Promise<ChangePasswordResponse> {
    const { data } = await apiClient.patch('/api/users/me/password', body);
    return data;
  },

  async forgotPassword(body: ForgotPasswordBody): Promise<ForgotPasswordResponse> {
    const { data } = await apiClient.post('/api/users/forgot-password', body);
    return data;
  },

  async resetPassword(body: ResetPasswordBody): Promise<ResetPasswordResponse> {
    const { data } = await apiClient.post('/api/users/reset-password', body);
    return data;
  },

  async toggleLike(componentId: string): Promise<ToggleLikeResponse> {
    const { data } = await apiClient.post(`/api/users/me/likes/${componentId}`);
    return data;
  },

  async getFavorites(): Promise<GetFavoritesResponse> {
    const { data } = await apiClient.get('/api/users/me/favorites');
    return data;
  },
};

export default usersService;
