// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type UpdateProfileDto = Record<string, unknown>;

export type ChangePasswordDto = Record<string, unknown>;

export type ForgotPasswordDto = Record<string, unknown>;

export type ResetPasswordDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /users/me — response */
export type GetProfileResponse = unknown;

/** PATCH /users/me — response */
export type UpdateProfileResponse = unknown;
/** PATCH /users/me — payload */
export type UpdateProfileBody = UpdateProfileDto;

/** PATCH /users/me/password — response */
export type ChangePasswordResponse = unknown;
/** PATCH /users/me/password — payload */
export type ChangePasswordBody = ChangePasswordDto;

/** POST /users/forgot-password — response */
export type ForgotPasswordResponse = unknown;
/** POST /users/forgot-password — payload */
export type ForgotPasswordBody = ForgotPasswordDto;

/** POST /users/reset-password — response */
export type ResetPasswordResponse = unknown;
/** POST /users/reset-password — payload */
export type ResetPasswordBody = ResetPasswordDto;

/** POST /users/me/likes/{componentId} — response */
export type ToggleLikeResponse = unknown;

/** GET /users/me/favorites — response */
export type GetFavoritesResponse = unknown;
